name: forutonafront
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+6

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # add dependency for Firebase Core
  firebase_core: ^0.4.3+1
  # add dependency for Firebase Core
  firebase_core_web: ^0.1.1+1
  #Url 웹페이지를 띄우기 위해서 사용
  url_launcher: ^5.4.1
  # add dependency for Google Analytics for Firebase
  firebase_analytics: ^5.0.2
  #NaverLogin을 위해서 사용
  flutter_naver_login: ^1.2.0
  #Firebase 인증을 위해서 사용
  firebase_auth: ^0.15.5+3
  #FaceBook인증을 위해서 사용
  flutter_facebook_login: ^3.0.0
  #추후 다국적 언어 지원에 사용
  flutter_localizations: # add this
    sdk: flutter
  #JSON 직렬화에 사용
  json_annotation:
  #카메라에서 이미지를 찍고 해당 사진을 리턴 받기 위해서 사용
  image_picker: ^0.6.5
  #비동기 처리에 필요
  async: ^2.3.0
  #GoogleMap
  google_maps_flutter: ^1.0.6
  #GPS 지도 정보를 사용하기 위해서 사용
  geolocator: ^5.3.1
  #태그 랭킹등에서 사용
  flutter_swiper: ^1.1.6
  #허가 관리
  permission_handler: ^3.3.0
  #전화 번호 입력을 할때 사용 GUI Lib
  international_phone_input: ^1.0.2
  uuid: ^2.0.1
  #인증 문자 메세지에서 사용
#  sms_receiver:
#    git:
#      url: https://github.com/kimbakcho/flutter_sms_receiver
  #FCM에 사용
  firebase_messaging: ^6.0.16
  #사진을 여러장 선택 할 필요가 있을때 사용
  multi_image_picker: ^4.6.0
  #Kakao 로그인 할때 사용
  kakao_flutter_sdk: ^0.5.2
  #내부 Native Notication을 사용하기위한 사용
  flutter_local_notifications: ^1.4.4+2
  #큐브의 에니메이션 효과등 복잡한 애니메이션을 Flare를 사용하여 처리기위해서 사용
  flare_flutter: ^1.8.3
  #KeyBarod 나타 날때  UI 변화를 주기 위해서 사용
  flutter_keyboard_visibility: ^2.0.0
  #Emun을 스트링으로 변환 시키기 위해 사용
  enum_to_string: ^1.0.8
  #backEnd 서버와 Http 통신하기 위해서 사용
  dio: ^3.0.8
  #토스트 메세지를 띄울때 사용
  fluttertoast: ^3.1.3
  #유튜브 정보를 얻어 오는데 사용
  youtube_explode_dart: ^1.0.0
  #코딩 패턴 사용
  provider: ^4.1.3
  #각종 이미지들을 확대 축소 가능하고 슬라이드로 보여주는데서 사용
  photo_view: ^0.9.2
  # 검색시 히스토리 저장 목적으로 사용
  shared_preferences: ^0.5.6+3
  #location 허가용
  location: ^3.0.2
  #AutoComPlete 기능을 위해 사용
  google_place: ^0.3.0
  #게시판등에서 html Viwer 목적으로 사용
  flutter_webview_plugin: ^0.3.11
  #Youtube 등 앱을 실행하기 위해서 사용
  android_intent:
  #googlefont 사용
  google_fonts: ^1.0.0
  #youtube VideoID Paser
  youtube_parser: ^1.1.0
  #이미지 압축을 위해서 사용
  flutter_image_compress: ^0.6.8
  #이미지 MetaData 를 추출 위해서 사용
  image: ^2.1.12
  #이미지 캐쉬 및 로딩에 사용
  cached_network_image: ^2.2.0+1
  #Mutex GPS 요청 사항이 Mutex 하지 않을때 Native 에서 에러나서 사용함
  mutex: ^1.0.3
  #test할때 사용
  mockito: ^4.1.1
  #Native Background Plugin 목적으로 사용
  background_fetch: ^0.6.0
  #statusBarColor 변경을 목적으로 사용
  flutter_statusbarcolor: ^0.2.3
  #인터넷 접속 가능 여부 판단 목적으로 사용
  data_connection_checker: ^0.3.4
  # add injectable to your dependencies
  injectable: ^1.0.5
  #의존성 주입을 위해 사용
  get_it: ^5.0.3
  #App의 로컬 파일 경로를 얻기 위해 사용
  path_provider: ^1.6.11
  #설치된 App 확인
  flutter_package_manager: ^0.2.0
  #Text된 컨텐츠 에서 select 가능 하고 link을 열기 위해 사용
  selectable_autolink_text: ^1.3.3
  #좋아요 싫어요 % 표시
  percent_indicator: ^2.1.5
  #ModalDraower 에 사용
  modal_bottom_sheet: ^1.0.0+1
  #Svg 파일 로딩에 사용
  flutter_svg: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # add the generator to your dev_dependencies
  injectable_generator:
  build_runner:
  build_test:
  json_serializable:


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:

  assets:
    - assets/
    - assets/MarkesImages/
    - assets/Rive/
    - assets/Brand/
    - assets/MainImage/
    - assets/LoginIcon/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Noto Sans CJK KR
      fonts:
        - asset: fonts/NotoSansKR-Regular.otf
        - asset: fonts/NotoSansKR-Medium.otf
          weight: 500
        - asset: fonts/NotoSansKR-Bold.otf
          weight: 700
    - family: Gibson
      fonts:
        - asset: fonts/gibson-Regular.ttf
        - asset: fonts/gibson-bold.ttf
          weight: 700
    - family: ForutonaIcon
      fonts:
        - asset: fonts/ForutonaIcon.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
