package com.wing.forutonafront;

import java.util.Date;

public class Userinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserInfo.Uid
     *
     * @mbg.generated
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserInfo.NickName
     *
     * @mbg.generated
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserInfo.ProfilePicktureUrl
     *
     * @mbg.generated
     */
    private String profilepicktureurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserInfo.Sex
     *
     * @mbg.generated
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserInfo.AgeDate
     *
     * @mbg.generated
     */
    private Date agedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserInfo.Email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserInfo.ForutonaAgree
     *
     * @mbg.generated
     */
    private Byte forutonaagree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserInfo.PrivateAgree
     *
     * @mbg.generated
     */
    private Byte privateagree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserInfo.PositionAgree
     *
     * @mbg.generated
     */
    private Byte positionagree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserInfo.MartketingAgree
     *
     * @mbg.generated
     */
    private Byte martketingagree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserInfo.AgeLimitAgree
     *
     * @mbg.generated
     */
    private Byte agelimitagree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserInfo.SnsService
     *
     * @mbg.generated
     */
    private String snsservice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserInfo.Phonenumber
     *
     * @mbg.generated
     */
    private String phonenumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserInfo.IsoCode
     *
     * @mbg.generated
     */
    private String isocode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserInfo.latitude
     *
     * @mbg.generated
     */
    private Double latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserInfo.longitude
     *
     * @mbg.generated
     */
    private Double longitude;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserInfo.Uid
     *
     * @return the value of UserInfo.Uid
     *
     * @mbg.generated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserInfo.Uid
     *
     * @param uid the value for UserInfo.Uid
     *
     * @mbg.generated
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserInfo.NickName
     *
     * @return the value of UserInfo.NickName
     *
     * @mbg.generated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserInfo.NickName
     *
     * @param nickname the value for UserInfo.NickName
     *
     * @mbg.generated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserInfo.ProfilePicktureUrl
     *
     * @return the value of UserInfo.ProfilePicktureUrl
     *
     * @mbg.generated
     */
    public String getProfilepicktureurl() {
        return profilepicktureurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserInfo.ProfilePicktureUrl
     *
     * @param profilepicktureurl the value for UserInfo.ProfilePicktureUrl
     *
     * @mbg.generated
     */
    public void setProfilepicktureurl(String profilepicktureurl) {
        this.profilepicktureurl = profilepicktureurl == null ? null : profilepicktureurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserInfo.Sex
     *
     * @return the value of UserInfo.Sex
     *
     * @mbg.generated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserInfo.Sex
     *
     * @param sex the value for UserInfo.Sex
     *
     * @mbg.generated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserInfo.AgeDate
     *
     * @return the value of UserInfo.AgeDate
     *
     * @mbg.generated
     */
    public Date getAgedate() {
        return agedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserInfo.AgeDate
     *
     * @param agedate the value for UserInfo.AgeDate
     *
     * @mbg.generated
     */
    public void setAgedate(Date agedate) {
        this.agedate = agedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserInfo.Email
     *
     * @return the value of UserInfo.Email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserInfo.Email
     *
     * @param email the value for UserInfo.Email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserInfo.ForutonaAgree
     *
     * @return the value of UserInfo.ForutonaAgree
     *
     * @mbg.generated
     */
    public Byte getForutonaagree() {
        return forutonaagree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserInfo.ForutonaAgree
     *
     * @param forutonaagree the value for UserInfo.ForutonaAgree
     *
     * @mbg.generated
     */
    public void setForutonaagree(Byte forutonaagree) {
        this.forutonaagree = forutonaagree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserInfo.PrivateAgree
     *
     * @return the value of UserInfo.PrivateAgree
     *
     * @mbg.generated
     */
    public Byte getPrivateagree() {
        return privateagree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserInfo.PrivateAgree
     *
     * @param privateagree the value for UserInfo.PrivateAgree
     *
     * @mbg.generated
     */
    public void setPrivateagree(Byte privateagree) {
        this.privateagree = privateagree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserInfo.PositionAgree
     *
     * @return the value of UserInfo.PositionAgree
     *
     * @mbg.generated
     */
    public Byte getPositionagree() {
        return positionagree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserInfo.PositionAgree
     *
     * @param positionagree the value for UserInfo.PositionAgree
     *
     * @mbg.generated
     */
    public void setPositionagree(Byte positionagree) {
        this.positionagree = positionagree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserInfo.MartketingAgree
     *
     * @return the value of UserInfo.MartketingAgree
     *
     * @mbg.generated
     */
    public Byte getMartketingagree() {
        return martketingagree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserInfo.MartketingAgree
     *
     * @param martketingagree the value for UserInfo.MartketingAgree
     *
     * @mbg.generated
     */
    public void setMartketingagree(Byte martketingagree) {
        this.martketingagree = martketingagree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserInfo.AgeLimitAgree
     *
     * @return the value of UserInfo.AgeLimitAgree
     *
     * @mbg.generated
     */
    public Byte getAgelimitagree() {
        return agelimitagree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserInfo.AgeLimitAgree
     *
     * @param agelimitagree the value for UserInfo.AgeLimitAgree
     *
     * @mbg.generated
     */
    public void setAgelimitagree(Byte agelimitagree) {
        this.agelimitagree = agelimitagree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserInfo.SnsService
     *
     * @return the value of UserInfo.SnsService
     *
     * @mbg.generated
     */
    public String getSnsservice() {
        return snsservice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserInfo.SnsService
     *
     * @param snsservice the value for UserInfo.SnsService
     *
     * @mbg.generated
     */
    public void setSnsservice(String snsservice) {
        this.snsservice = snsservice == null ? null : snsservice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserInfo.Phonenumber
     *
     * @return the value of UserInfo.Phonenumber
     *
     * @mbg.generated
     */
    public String getPhonenumber() {
        return phonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserInfo.Phonenumber
     *
     * @param phonenumber the value for UserInfo.Phonenumber
     *
     * @mbg.generated
     */
    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber == null ? null : phonenumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserInfo.IsoCode
     *
     * @return the value of UserInfo.IsoCode
     *
     * @mbg.generated
     */
    public String getIsocode() {
        return isocode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserInfo.IsoCode
     *
     * @param isocode the value for UserInfo.IsoCode
     *
     * @mbg.generated
     */
    public void setIsocode(String isocode) {
        this.isocode = isocode == null ? null : isocode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserInfo.latitude
     *
     * @return the value of UserInfo.latitude
     *
     * @mbg.generated
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserInfo.latitude
     *
     * @param latitude the value for UserInfo.latitude
     *
     * @mbg.generated
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserInfo.longitude
     *
     * @return the value of UserInfo.longitude
     *
     * @mbg.generated
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserInfo.longitude
     *
     * @param longitude the value for UserInfo.longitude
     *
     * @mbg.generated
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }
}