/// Flutter icons ForutonaIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ForutonaIcon
///      fonts:
///       - asset: fonts/ForutonaIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ForutonaIcon {
  ForutonaIcon._();

  static const _kFontFam = 'ForutonaIcon';
  static const _kFontPkg = null;

  static const IconData issue = const IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quest = const IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mainfab = const IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData napoint = const IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumbsdown = const IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumbsup = const IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData whatshot = const IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData accesstime = const IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment = const IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pointdash = const IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData path = const IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icninboxdark = const IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noballinbox = const IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smallyoupoint = const IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contributor = const IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sponsorcount = const IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bigyoupoint = const IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData visibility = const IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData setting = const IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = const IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icn_send = const IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData replysplitbottom = const IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData replysplittop = const IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData panedit = const IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData removepath = const IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = const IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData videoattach = const IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tagadd = const IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData yplay = const IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = const IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bigexppoint = const IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smallexppoint = const IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData badge = const IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell = const IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = const IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cog = const IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_arrow = const IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group = const IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData h003top = const IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list = const IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData repost = const IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map = const IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData officialchannel = const IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = const IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = const IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData social = const IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash = const IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = const IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet = const IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData anchor = const IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData joystick = const IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData searchbackbtn = const IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData donate_heart = const IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = const IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData envelope = const IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gift = const IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil = const IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData run = const IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData transfer_alt = const IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData undo = const IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData x = const IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData badge_1 = const IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData badge_chec = const IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell_1 = const IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell_off = const IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bullseye = const IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = const IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_right = const IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coin = const IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coin_stack = const IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credit_card = const IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
