/// Flutter icons ForutonaIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ForutonaIcon
///      fonts:
///       - asset: fonts/ForutonaIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ForutonaIcon {
  ForutonaIcon._();

  static const _kFontFam = 'ForutonaIcon';

  static const IconData issue = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData quest = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData mainfab = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData napoint = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData thumbsdown = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData thumbsup = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData whatshot = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData accesstime = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData comment = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData pointdash = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData path = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData icninboxdark = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData noballinbox = const IconData(0xe80c, fontFamily: _kFontFam);
}
